### ISSUE TITLE
External WPF client sample for ServiceFabric.WcfCalc example - WCFCommunication Listener

### ISSUE THREAD

**Issue by valcs007** [loekd/ServiceFabric.WcfCalc#1]
Hi,

I have used WCFCommunication Listener for my microservice (Similar to Calc Example). Can you please give me some sample project (WPF external client) for accessing microservice?

**PS:** I saw examples of external client using ServiceProx for Remote listeners but i didn't see any examples for accessing microservice which uses WCFCommunicationListener

**Comment by loekd** [comment]
You can access it the same way you'd access any other WCF service. For example, provided you expose the metadata endpoint, you can use Visual Studio to generate a regular Service Proxy using ['add service reference'](https://msdn.microsoft.com/en-us/library/bb628652.aspx).
